Vagrant.configure("2") do |config|

    config.vm.box = "hashicorp/precise64"

    config.vm.network :private_network, ip: "192.168.33.103"

    config.vm.provision :puppet do |puppet|
        puppet.module_path = "modules"
    end

    config.vm.synced_folder "app", "/vagrant"

    # Comment the line below if you are using vagrant < 1.6
    config.vm.post_up_message = "Environment Ready. Check http://192.168.33.103"
end